# Generated by Django 4.2.11 on 2025-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20221231_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_mail',
            field=models.TextField(default='Hi there!\n\nThis is a confirmation of your application to <a href="http://djangogirls.org/{city}">Nordic Walk United {CITY}</a>. Yay! That\'s a huge step already, we\'re proud of you!\n\nMind that this is not a confirmation of participation in the event, but a confirmation that we received your application.\n\nYou\'ll receive an email from the team that organizes Nordic Walk United {CITY} soon. You can always reach them by answering to this email or by writing to {your event mail}.\nFor your reference, we\'re attaching your answers below.\n\nHugs, cupcakes and high-fives!\nNordic Walk United', help_text='Mail will be sent from your event mail.\nAlso the answers will be attached.'),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_description',
            field=models.TextField(default="Yay! We're so excited you want to be a part of our workshop. Please mind that filling out the form below does not give you a place on the workshop, but a chance to get one. The application process is open from {INSERT DATE} until {INSERT DATE}. If you're curious about the criteria we use to choose applicants, you can read about it on <a href='http://blog.djangogirls.org/post/91067112853/djangogirls-how-we-scored-applications'>Nordic Walk United blog</a>. Good luck!"),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_header',
            field=models.CharField(default='Apply for a spot at Nordic Walk United [City]!', max_length=255),
        ),
    ]
