# Generated by Django 4.2.11 on 2025-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240130_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nwgroup',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
