# Generated by Django 4.2.11 on 2025-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_nwgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_description',
            field=models.TextField(blank=True, default='Nordic Walking United is a one-day walk ', verbose_name='description'),
        ),
    ]
