# Generated by Django 4.2.11 on 2025-04-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_event_page_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_description',
            field=models.TextField(blank=True, default='Nordic Walk United is a one-day event in Nordic Walk United.', verbose_name='description'),
        ),
    ]
