# Generated by Django 4.2.11 on 2025-04-12 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
