# Generated by Django 5.2 on 2025-04-13 20:16

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_uuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Basic Moderate'), (0, 'Basic Easy'), (2, 'Wellbeing Walk')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='preview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(0, 'miles'), (1, 'km')], default=0),
        ),
    ]
