# Generated by Django 5.2 on 2025-04-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_difficulty_event_distance_event_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Basic Easy'), (1, 'Basic Moderate'), (2, 'Wellbeing Walk')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(1, 'km'), (0, 'miles')], default=0),
        ),
    ]
