# Generated by Django 5.2 on 2025-04-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_event_difficulty_alter_event_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Basic Easy'), (2, 'Wellbeing Walk'), (1, 'Basic Moderate')], default=0),
        ),
    ]
