# Generated by Django 5.2 on 2025-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_event_difficulty_alter_event_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.IntegerField(choices=[(0, 'Under 18'), (18, '18-24'), (25, '25-34'), (35, '35-44'), (45, '45-54'), (55, '55-64'), (65, '65 or over')], default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(2, 'Wellbeing Walk'), (0, 'Basic Easy'), (1, 'Basic Moderate')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(0, 'miles'), (1, 'km')], default=0),
        ),
    ]
