# Generated by Django 5.2 on 2025-05-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_event_participants_alter_event_unit_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Basic Moderate'), (2, 'Wellbeing Walk'), (0, 'Basic Easy')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(1, 'km'), (0, 'miles')], default=0),
        ),
    ]
