# Generated by Django 5.2 on 2025-05-21 21:53

import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_event_difficulty_alter_event_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='preview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='avatar.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to=''),
        ),
    ]
