# Generated by Django 5.2 on 2025-05-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_submission_preview_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Basic Moderate'), (0, 'Basic Easy'), (2, 'Wellbeing Walk')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(0, 'miles'), (1, 'km')], default=0),
        ),
    ]
