# Generated by Django 5.2 on 2025-06-10 18:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_event_difficulty_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(2, 'Wellbeing Walk'), (1, 'Basic Moderate'), (0, 'Basic Easy')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='preview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Picture'),
        ),
    ]
