# Generated by Django 5.2 on 2025-06-10 22:53

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_event_country_alter_event_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='imgpresent',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 500], upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Basic Easy'), (2, 'Wellbeing Walk'), (1, 'Basic Moderate')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(0, 'miles'), (1, 'km')], default=0),
        ),
    ]
