# Generated by Django 5.2 on 2025-06-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_event_difficulty_alter_event_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Basic Moderate'), (2, 'Wellbeing Walk'), (0, 'Basic Easy')], default=0),
        ),
    ]
