# Generated by Django 5.2 on 2025-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_event_difficulty_alter_event_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(2, 'Wellbeing Walk'), (1, 'Basic Moderate'), (0, 'Basic Easy')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(1, 'km'), (0, 'miles')], default=0),
        ),
    ]
