# Generated by Django 5.2 on 2025-06-11 03:21

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_event_difficulty_alter_event_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='imgpresent',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 500], upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Basic Easy'), (1, 'Basic Moderate'), (2, 'Wellbeing Walk')], default=0),
        ),
    ]
