# Generated by Django 5.2 on 2025-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_submission_imgpresent_alter_event_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='imgpresent',
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Basic Easy'), (2, 'Wellbeing Walk'), (1, 'Basic Moderate')], default=0),
        ),
    ]
