# Generated by Django 5.2 on 2025-06-16 17:00

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_submission_imgpresent_alter_event_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.IntegerField(choices=[(0, 'miles'), (1, 'km')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='imgpresent',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 500], upload_to='submissions/'),
        ),
    ]
