# Generated by Django 5.0.6 on 2025-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_nwu_manual_alter_user_options_alter_event_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(1, "km"), (0, "miles")], default=0),
        ),
    ]
