# Generated by Django 5.0.6 on 2025-11-15 19:27

import core.validators
import django_ckeditor_5.fields
import django_date_extensions.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_event_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=django_date_extensions.fields.ApproximateDateField(
                validators=[core.validators.validate_approximatedate]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.CharField(max_length=30, null=True, verbose_name="Duration"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.CharField(max_length=30, null=True, verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(0, "miles"), (1, "km")], default=0),
        ),
        migrations.AlterField(
            model_name="nwu_manual",
            name="audience",
            field=models.CharField(
                choices=[
                    ("general", "General Information"),
                    ("participant", "For Participants"),
                    ("team", "For Team Members / Organizers"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nwu_manual",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Text"
            ),
        ),
    ]
