# Generated by Django 5.0.6 on 2025-11-18 18:29

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_event_date_alter_event_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Moderate"),
                    (0, "Basic Easy"),
                    (2, "Wellbeing Walk"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(1, "km"), (0, "miles")], default=0),
        ),
        migrations.AlterField(
            model_name="submission",
            name="imgpresent",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[700, 522],
                upload_to="submissions/",
            ),
        ),
    ]
