# Generated by Django 5.0.6 on 2025-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_event_difficulty_alter_event_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rules_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="rules_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (0, "Basic Easy"),
                    (2, "Wellbeing Walk"),
                    (1, "Basic Moderate"),
                ],
                default=0,
            ),
        ),
    ]
