# Generated by Django 5.0.6 on 2025-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_submission_imgpresent_alter_user_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (2, "Wellbeing Walk"),
                    (1, "Basic Moderate"),
                    (0, "Basic Easy"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="nwu_manual",
            name="audience",
            field=models.CharField(
                choices=[
                    ("handbook", "Handbook"),
                    ("participant", "For Participants"),
                    ("team", "For Team Members / Organizers"),
                    ("general", "General Information"),
                ],
                default="handbook",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
