# Generated by Django 5.0.6 on 2025-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_event_difficulty_alter_nwu_manual_audience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Moderate"),
                    (2, "Wellbeing Walk"),
                    (0, "Basic Easy"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(0, "miles"), (1, "km")], default=0),
        ),
    ]
