# Generated by Django 5.0.6 on 2025-12-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_event_difficulty_alter_event_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (0, "Basic Easy"),
                    (2, "Wellbeing Walk"),
                    (1, "Basic Moderate"),
                ],
                default=0,
            ),
        ),
    ]
