# Generated by Django 5.0.6 on 2026-01-22 15:27

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_event_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Moderate"),
                    (0, "Basic Easy"),
                    (2, "Wellbeing Walk"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="avatar.png",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[200, 200],
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
