# Generated by Django 5.0.6 on 2026-01-23 21:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_event_difficulty_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="event",
            name="effort_level",
            field=models.IntegerField(
                choices=[
                    (0, "Low – gentle pace, relaxed breathing"),
                    (1, "Moderate – steady pace, deeper breathing at times"),
                    (2, "Higher – sustained effort, stronger cardiovascular work"),
                ],
                default=0,
                verbose_name="Effort Level",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="elevation",
            field=models.IntegerField(
                choices=[
                    (0, "Mostly flat – minimal elevation change"),
                    (1, "Some elevation – gentle hills"),
                    (2, "Significant elevation – steeper hills"),
                ],
                default=0,
                verbose_name="Elevation",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="walking_surface",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("AS", "Concrete / Asphalt"),
                    ("PV", "Paved path (mixed hard surface)"),
                    ("GR", "Gravel"),
                    ("DI", "Dirt / packed earth"),
                    ("GS", "Grass"),
                    ("SA", "Sand"),
                    ("UN", "Uneven surface (roots, rocks, irregular ground)"),
                    ("SE", "Seasonal surface (snow, ice, mud, wet leaves)"),
                ],
                max_length=8,
                verbose_name="Walking Surface",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(0, "miles"), (1, "km")], default=0),
        ),
    ]
