# Generated by Django 5.0.6 on 2026-01-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_remove_event_difficulty_event_effort_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(1, "km"), (0, "miles")], default=0),
        ),
    ]
