# Generated by Django 5.0.6 on 2026-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_event_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(0, "miles"), (1, "km")], default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Zip Code"),
        ),
    ]
