# Generated by Django 5.0.6 on 2026-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_event_unit_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees_count",
            field=models.IntegerField(
                blank=True,
                choices=[("MA", "Massachusetts "), ("FL", "Florida")],
                null=True,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(1, "km"), (0, "miles")], default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
    ]
