# Generated by Django 5.0.6 on 2026-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_event_attendees_count_alter_event_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="state",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of attendees"
            ),
        ),
    ]
