# Generated by Django 5.0.6 on 2026-02-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_event_state_alter_event_attendees_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="unit",
            field=models.IntegerField(choices=[(0, "miles"), (1, "km")], default=0),
        ),
    ]
