# Generated by Django 5.0.6 on 2026-02-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_event_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Two-letter state code (e.g., MA, FL)",
                max_length=2,
                null=True,
            ),
        ),
    ]
