# Generated by Django 5.0.6 on 2026-02-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_event_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="addr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
