# Generated by Django 4.2.11 on 2025-02-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0011_alter_eventapplication_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='nwgroup',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
