# Generated by Django 4.2.11 on 2025-03-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_nwgroup'),
        ('organize', '0012_eventapplication_nwgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='previous_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_applications_organize', to='core.event'),
        ),
    ]
