# Generated by Django 4.2.11 on 2025-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0013_alter_eventapplication_previous_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='involvement',
            field=models.CharField(max_length=100, verbose_name='Involvement in Nordic Walk United'),
        ),
    ]
