# Generated by Django 5.2 on 2025-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactemail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemail',
            name='contact_type',
            field=models.CharField(choices=[('chapter', 'Nordic Walking United Local Organizers'), ('support', 'Nordic Walking United (Support Team)')], default='chapter', max_length=20, verbose_name='Who do you want to contact?'),
        ),
    ]
