# Generated by Django 5.0.6 on 2025-10-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contactemail_contact_type"),
        ("core", "0038_nwu_manual_alter_user_options_alter_event_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactemail",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("question", "Nordic Walking United Local Organizers"),
                    ("support", "Nordic Walking United (Support Team)"),
                ],
                default="question",
                max_length=20,
                verbose_name="Who do you want to contact?",
            ),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="required for contacting  local organizers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.event",
            ),
        ),
    ]
