# Generated by Django 5.0.6 on 2025-11-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_replied_at_comment_replied_by_comment_reply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
