# Generated by Django 5.0.6 on 2025-12-05 18:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="images",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Images"
            ),
        ),
    ]
