# Generated by Django 5.0.6 on 2025-12-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reactions_heart",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="reactions_leaf",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="reactions_smile",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
